## ALMUZAHIM NASEEF MUHAMAD S24B38/006 B30296

## THEORY PART OF ASSIGNMENT

TOTAL POPULATION WAS 45.9 MILLION

MALE POPULATION WAS 21.6 MILLION

FEMALE POPULATION WAS 24.3 MILLION

sex ratio by region,population density,average household size,regional population growth,population distribution by region,population by age group, population size by sex

## shapiro wilks test

shapiro wilks test is used when cheching the normality of data. arandom sample is taken from the populationand the test performed. this allows one to know or have an idea about the population distribution, whether its is normally distributed or not

## one_way ANOVA TEST

ANOVA TEST IS  a statistical method that is used to compare the means of two or more groups. it is a parametric test which is used when the data is normally distributed.

the one way ANOVA is used to determine whether thre is sinificant difference between the means of three or more populations,it will compare the population distribution of the regions by examining whether their means are statistically equal


## pearson's correlation test

used when finding the linear coorelation betweeen two variables. it is bivarient in nature.it will be used to find the relationship between populationdistribution by region and population density , both are assumed to be normally ditributed since it is also a parametric functuion

##  cummulative distribution function

the cuumulative distribution function tells us the probability of randomly selcting a value from the population that is less than or equal to the point. the data is first sorted in ascending order, then for the each point the prportion of data points that fall at or below the value give us the probability of each point

for discrete data the cdf will have jumps at each point while for continous it will be a smooth curve

## poisson distribution

it predicts the number of events occuring within a given interval. it handles strictly discrete variables.



 ## PRACTICAL PART OF ASSIGNMENT

In [46]:
#importation of necessary libraries
import warnings
warnings.filterwarnings("ignore")
import pandas as pd


I imported the necessary libraries that will be used

importation of dataset 

In [21]:
pd.read_csv("Students.csv")

Marital status;Application mode;Application order;Course;"Daytime/evening attendance\t";Previous qualification;Previous qualification (grade);Nacionality;Mother's qualification;Father's qualification;Mother's occupation;Father's occupation;Admission grade;Displaced;Educational special needs;Debtor;Tuition fees up to date;Gender;Scholarship holder;Age at enrollment;International;Curricular units 1st sem (credited);Curricular units 1st sem (enrolled);Curricular units 1st sem (evaluations);Curricular units 1st sem (approved);Curricular units 1st sem (grade);Curricular units 1st sem (without evaluations);Curricular units 2nd sem (credited);Curricular units 2nd sem (enrolled);Curricular units 2nd sem (evaluations);Curricular units 2nd sem (approved);Curricular units 2nd sem (grade);Curricular units 2nd sem (without evaluations);Unemployment rate;Inflation rate;GDP;Target
0     1;17;5;171;1;1;122.0;1;19;12;5;9;127.3;1;0;0;1...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
1     1;15;1;9254;1;1;160.0;1;1;3;3;3;142.5;1;0;0;0;...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
2     1;1;5;9070;1;1;122.0;1;37;37;9;9;124.8;1;0;0;0...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
3     1;17;2;9773;1;1;122.0;1;38;37;5;3;119.6;1;0;0;...                                                                                                                                                                                                                                                                                                                                                                                                                              

In [47]:
#delimiter a character used to sepearate elements with strings or data structures
pd.read_csv("Students.csv",delimiter=';')
students=pd.read_csv("Students.csv",delimiter=';')
students

Marital status  Application mode  Application order  Course  \
0                  1                17                  5     171   
1                  1                15                  1    9254   
2                  1                 1                  5    9070   
3                  1                17                  2    9773   
4                  2                39                  1    8014   
...              ...               ...                ...     ...   
4419               1                 1                  6    9773   
4420               1                 1                  2    9773   
4421               1                 1                  1    9500   
4422               1                 1                  1    9147   
4423               1                10                  1    9773   

      Daytime/evening attendance\t  Previous qualification  \
0                                1                       1   
1                                1                       1   
2                                1                       1   
3                                1                       1   
4                                0                       1   
...                            ...                     ...   
4419                             1                       1   
4420                             1                       1   
4421                             1                       1   
4422                             1                       1   
4423                             1                       1   

      Previous qualification (grade)  Nacionality  Mother's qualification  \
0                              122.0            1                      19   
1                              160.0            1                       1   
2                              122.0            1                      37   
3                              122.0            1                      38   
4                              100.0            1                      37   
...                              ...          ...                     ...   
4419                           125.0            1                       1   
4420                           120.0          105                       1   
4421                           154.0            1                      37   
4422                           180.0            1                      37   
4423                           152.0           22                      38   

      Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                         12  ...                                    0   
1                          3  ...                                    0   
2                         37  ...                                    0   
3                         37  ...                                    0   
4                         38  ...                                    0   
...                      ...  ...                                  ...   
4419                       1  ...                                    0   
4420                       1  ...                                    0   
4421                      37  ...                                    0   
4422                      37  ...                                    0   
4423                      37  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                            

the dilimeter function enables the csv file to be in a tabular form that enables us to carryout commands on it

In [23]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance	                     4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64  
 8   Mother's qualification                          4424 non-null   int64  
 9   Father's qualification                   

In [48]:
#dataset had no missing values
students.isnull().sum()

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance\t                      0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrol

the dataset had no missing values

getting number enrolled under target

## question two

In [39]:
#this gets the total number of students
total_target=students['Target'].count()
total_target

np.int64(4424)

total number of students under target are 4424

In [40]:
#i got the people who were enrolled under the variable target
en=students[students['Target']=='Enrolled']['Target'].count()
en

np.int64(794)

total enrolled students under target are 794

In [27]:
probability_enrolled=en/total_target
print(f"the probability student is enrolled under target is {probability_enrolled}")

the probability student is enrolled under target is 0.1794755877034358


## question three


In [28]:
number_graduates=students[students['Target']=='Graduate']['Target'].count()
number_graduates

np.int64(2209)

In [29]:
number_one=students[students['Marital status']==1]['Marital status'].count()
number_one

np.int64(3919)

In [42]:
# getting the intersection of graduate and marital satus of 1
filterd=(students['Target']=='Graduate')&(students["Marital status"]==1)
filterd

0       False
1        True
2       False
3        True
4       False
        ...  
4419     True
4420    False
4421    False
4422     True
4423     True
Length: 4424, dtype: bool

In [31]:
#this is the intersection of Graduate and Marital status of 1 it will help us in conditional probability
number_graduated_marital_status=students[filterd]['Target'].count()
number_graduated_marital_status

np.int64(2015)

In [32]:
probability=number_graduated_marital_status/number_one
probability
print(f"the probability of student being a graduate and having amarital status of one is {probability}")

the probability of student being a graduate and having amarital status of one is 0.514161775963256


## question four

marinal probability is the probability of a single evnt occuring

In [33]:
total_students=len(students)
total_students

4424

In [43]:
#value counts will enable us to get the length of each variable in the dataset
all_ages=students['Age at enrollment'].value_counts()
all_ages

Age at enrollment
18    1036
19     911
20     599
21     322
22     174
24     131
23     108
26      94
25      93
27      91
28      83
29      66
32      61
34      60
31      55
35      49
30      49
33      45
37      42
39      38
36      35
41      31
38      29
43      25
40      23
45      22
44      21
47      18
50      16
42      13
49      13
46      12
48      11
51       7
54       7
53       7
17       5
55       5
52       4
59       3
58       3
57       2
60       2
61       1
70       1
62       1
Name: count, dtype: int64

In [44]:
#tis shows the individual probabilities of the variable
marginal_probability=all_ages/total_students
print(f"the marginal probability is,{marginal_probability}")

the marginal probability is,Age at enrollment
18    0.234177
19    0.205922
20    0.135398
21    0.072785
22    0.039331
24    0.029611
23    0.024412
26    0.021248
25    0.021022
27    0.020570
28    0.018761
29    0.014919
32    0.013788
34    0.013562
31    0.012432
35    0.011076
30    0.011076
33    0.010172
37    0.009494
39    0.008590
36    0.007911
41    0.007007
38    0.006555
43    0.005651
40    0.005199
45    0.004973
44    0.004747
47    0.004069
50    0.003617
42    0.002939
49    0.002939
46    0.002712
48    0.002486
51    0.001582
54    0.001582
53    0.001582
17    0.001130
55    0.001130
52    0.000904
59    0.000678
58    0.000678
57    0.000452
60    0.000452
61    0.000226
70    0.000226
62    0.000226
Name: count, dtype: float64


## question five


In [45]:
#this gets the number of people who are 18 and were enrolled
age_18=students[students['Age at enrollment']==18]['Age at enrollment'].count()
age_18

np.int64(1036)

In [36]:
probability_18=age_18/total_students
print(f"probability that age of enrollment is 18 is ,{probability_18}")

probability that age of enrollment is 18 is ,0.23417721518987342
